
DEFAULT:
  mongo_url: mongodb://localhost:27017
  mongo_database: core4dev

kernel:
  sys.conf:

logging:
  console_log_level: INFO
  console_log_format: '%%(asctime)s - %%(levelname)-8s - %%(message)s'
